### ISSUE TITLE
wasm-terminal: Extra output in QuickJS Prompting

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#107]
When running `if (3 ==3) { console.log('hello') }` We get the following:

<img width="1038" alt="Screen Shot 2019-10-09 at 09 50 33" src="https://user-images.githubusercontent.com/1448289/66505895-19709480-ea81-11e9-8bc2-a2b4f310d0c5.png">
<img width="482" alt="Screen Shot 2019-10-09 at 09 50 39" src="https://user-images.githubusercontent.com/1448289/66505897-19709480-ea81-11e9-9aee-10ca2bab6c29.png">

**Comment by torch2424** [comment]
Reported by Mark 😄

**Comment by syrusakbary** [comment]
This is now fixed in `master`. Closing the issue
