### ISSUE TITLE
wasm-terminal: CTRL+C Wipes current line

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#108]
Should preserve line, but push onto a new line 😄 

Reported by Nick 😄

**Comment by torch2424** [comment]
@nlewycky Actually, on my terminal, my CTRL+C Wipes the input. So if you don't mind, I'm going to close this as it works as expected? 🤔 

<img width="623" alt="Screen Shot 2019-10-10 at 4 56 51 PM" src="https://user-images.githubusercontent.com/1448289/66614830-4b682080-eb7f-11e9-9f81-b60cf45ac157.png">

**Comment by nlewycky** [comment]
You pressed `^C` on the line with `asdasdasdasd`? See how `asdasdasdasd` is still visible? That's not what happens when in the webassembly shell. I press `^C` and the line of text disappears. I wanted to see that line of text.

**Comment by torch2424** [comment]
Ohhhhhh Not on the next line? Cool, I can do that I'll reopen 😄
