### ISSUE TITLE
Wasm-terminal: Handle Composition / IME Events from Mobile Firefox and Sometimes Mobile Chrome

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#112]
It's actually a bug in firefox, so simply watch this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1587934

**Comment by torch2424** [comment]
Actually bug was resolved as it being a bug in the mdn example code? 🤔 

All in all, I think there is some weird behavior going on in mobile browsers concerning this. For example: https://stackoverflow.com/questions/42011740/event-preventdefault-not-working-for-android-chrome . Thus, we need to set the input using JS on every keypress, suing something like xterm's [onKey](https://xtermjs.org/docs/api/terminal/classes/terminal/#onkey).

However, I am going to make one more case for: https://davidwalsh.name/disable-autocorrect . Because this also does not seem to work in firefox mobile...

**Comment by Michael-F-Bryan** [comment]
I don't believe this is relevant now that we've rewritten the package as `@wasmer/sdk`.
