### ISSUE TITLE
wasmfs: Cannot read property 'inherits' of undefined

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer-js#134]
This error occurs when running `require('@wasmer/wasmfs')` in Node (tested on v12.11.0 and v8.9.1), and in the browser with Browserify.

What is the proper way to import it?

**Comment by corwin-of-amber** [comment]
Note: error seems to go away if I `npm uninstall parcel`. Notice that `parcel` (indirectly) uses `util` and `inherits`.

https://github.com/rollup/rollup/issues/2132

**Comment by torch2424** [comment]
@corwin-of-amber 

Hello! Thank you for catching and reporting this! We just confirmed this, and will have a fix out in a bit 😄 

Also, thank you for the supporting documentation so we can fix it! 👍 

Thank you!
