### ISSUE TITLE
[New Feature] Create support for framebuffer device in https://webassembly.sh

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#140]
It would be super cool to write out to the framebuffer file and see output on a canvas element on the screen.  People could write 2D visualizations, demoscene work, view files, and maybe if there's keyboard support one day play games in https://webassembly.sh

**How would this work?**

writing bytes to the file `/dev/fb0`

would setImageData on a canvas that covers the whole window

**how would you know how many bytes to write?**

read the file `/sys/class/graphics/fb0/virtual_size` would return size as a string as linux does eg "1920x1280" based off the current window dimensions

The canvas would be full window at maximum z height and pointer-events: none to be completely non interactable.

Exiting a program would clear the canvas so you don't have ghost images.

**Comment by torch2424** [comment]
@richardanaya Hello! This is a great idea! It's been something we have been researching, and will update this issue if we end up with any news 😄

**Comment by torch2424** [comment]
@richardanaya 

This is now available using the Experimental I/O Devices 😄 https://medium.com/wasmer/wasmer-io-devices-announcement-6f2a6fe23081

**Comment by richardanaya** [comment]
You rock!
