### ISSUE TITLE
[New Feature] Support raw keyboard events in https://webassembly.sh

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#141]
We need more low level access to the keyboard in order to create text based games.  Perhaps we can create some kind of file that can be read from to get raw keyboard events (key down and up)?
`/dev/input/rawkb` ?

**Comment by torch2424** [comment]
@richardanaya 

This is now available using the Experimental I/O Devices 😄 https://medium.com/wasmer/wasmer-io-devices-announcement-6f2a6fe23081
