### ISSUE TITLE
fd_read results in TypeError

### ISSUE THREAD

**Issue by TJKoury** [wasmerio/wasmer-js#145]
File writes work in Node (13.01), but reads throw this error:

```
 Cannot mix BigInt and other types, use explicit conversions
    at Object.readSync (fs.js:494:3)
```

The issue looks like it is at [this line](https://github.com/wasmerio/wasmer-js/blob/a218db120322b31a0d1a23067570db97d5df7e84/packages/wasi/lib/wasi.ts#L725) where `BigIntPolyfill` is being used to get the offset for reading from the file descriptor.

Not sure what the root of the problem might be.

**Comment by torch2424** [comment]
As your comment stated is this related to #135 ? Can we close this in favor of #135 ? 😄

**Comment by TJKoury** [comment]
Sure.  The root of the issue is using a bigNum with a Number, but the fix should remove that as an issue.

**Comment by torch2424** [comment]
Awesome, thank you @TJKoury 😄 !
