### ISSUE TITLE
wasmfs: ENOTDIR error escapes to top

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer-js#158]
If my C program is doing this:
```c
DIR *d = opendir("/home/a");
```

Where `/home/a` is a regular file, an error is thrown, terminating the program:
```
Error: ENOTDIR: not a directory, scandir '/home/a'
    at createError (worker.js:12995)
    at throwError (worker.js:13017)
    at Volume.readdirBase (worker.js:14477)
    at Volume.readdirSync (worker.js:14507)
    at worker.js:3558
    at worker.js:3104
    at wasiImport.<computed> (worker.js:3993)
```

`@wasmer/wasi` correctly handles `ENOENT` errors by returning `NULL` to the caller, but not `ENOTDIR`.

**Comment by syrusakbary** [comment]
That looks like a bug!
@corwin-of-amber would you like to help on a fix with a PR? :)

**Comment by torch2424** [comment]
@corwin-of-amber My apologies, just got back from Chrome Dev Summit. Did you still have an issue with this? I can try and help with a solution, and as @syrusakbary suggested, if you have the bandwidth and want to contribute that would be more than welcome! 

We can totally fix this on our end as well, just let us know 😄

**Comment by corwin-of-amber** [comment]
I haven't checked with changes from last week. I will take a look and try to fix it, I saw the point where WASI is checking for ENOENT so I think the check for ENOTDIR should go there as well.

**Comment by corwin-of-amber** [comment]
Seems like this has been fixed! Sorry for not pitching in earlier.

**Comment by torch2424** [comment]
@corwin-of-amber No worries! Thanks for confirming it has been fixed 😄 Closing...
