### ISSUE TITLE
Stdin working funny

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer-js#160]
Stdin in the terminal is working in a funky/hacky way.
We should solve this.

This things should work with any browser:
* `cowsay hello | lolcat | lolcat` (it only works in FF now)
* `qjs | lolcat`

**Comment by torch2424** [comment]
So `cowsay hello | lolcat | lolcat` works for me? I re-cloned the project, `npm install`, `npm run dev` and it worked?

<img width="752" alt="Screen Shot 2019-11-18 at 4 15 24 PM" src="https://user-images.githubusercontent.com/1448289/69104903-ae6e9200-0a1e-11ea-9f7a-8ce21279c405.png">
<img width="966" alt="Screen Shot 2019-11-18 at 4 15 15 PM" src="https://user-images.githubusercontent.com/1448289/69104904-ae6e9200-0a1e-11ea-9364-6ad9fbfda543.png">
<img width="720" alt="Screen Shot 2019-11-18 at 4 15 06 PM" src="https://user-images.githubusercontent.com/1448289/69104905-ae6e9200-0a1e-11ea-9415-3912eee21566.png">

**Comment by torch2424** [comment]
And `qjs | lolcat` works too? (When using a web worker)

<img width="721" alt="Screen Shot 2019-11-18 at 4 16 44 PM" src="https://user-images.githubusercontent.com/1448289/69104981-e5dd3e80-0a1e-11ea-9b78-aa65a750bcdd.png">
