### ISSUE TITLE
Support for wasi_snapshot_preview1 and future import namespaces

### ISSUE THREAD

**Issue by robinvanemden** [wasmerio/wasmer-js#168]
Wasmer-JS currently only supports the older `wasi_unstable` export namespace. 

Use of the newer `wasi_snapshot_preview1` export namespace gives to the following error:

```
index.js:60 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function
```

**Comment by robinvanemden** [comment]
Never mind! It is of course quite possible to just set:

```
  // Instantiate the WebAssembly file
  let { instance } = await WebAssembly.instantiate(wasmBytes, {
    wasi_snapshot_preview1: wasi.wasiImport
  });
```

Though this leaves, for instance, fuzzy matching to the JS developer.

**Comment by pshdevio** [comment]
Where does the `wasi` object come from ?
