### ISSUE TITLE
cli flag handling is unintuitive

### ISSUE THREAD

**Issue by mischnic** [wasmerio/wasmer-js#170]
1. An unhelpful error message (because the number of args isn't checked with `strict = false`):
```
$ wasmer-js run
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
```

2. 🤷‍♂
```sh
$ wasmer-js run --dir=/ test.wasi
```
is interpreted as `wasmer-js run --dir=/ --dir=test.wasi`

**Comment by syrusakbary** [comment]
Agreed, that's very bad parsing.

I suspect is caused by the package [`@oclif/command`](https://www.npmjs.com/package/@oclif/command).

**Comment by syrusakbary** [comment]
Perhaps we should change library for parsing the CLI args

**Comment by vshymanskyy** [comment]
Point 2 makes it unusable for me, when it comes to working with files.

**Comment by mischnic** [comment]
@vshymanskyy 

If you didn't figure this out yet, this does work: `wasmer-js run test.wasi --dir=/`

**Comment by vshymanskyy** [comment]
@mischnic thanks! It wasn't critical in my case, but thanks for providing a helpful hint here! ;)

**Comment by torch2424** [comment]
@syrusakbary Looked into this, and this is totally a bug on oclif, see here: https://github.com/oclif/oclif/issues/190

I've personally always used [minimist](https://www.npmjs.com/package/minimist). It's a little more barebones, but it does the expected behavior in our case so yeah? 😄 👍
