### ISSUE TITLE
wasm-transformer: crash in generate_trampolines_and_signatures

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer-js#176]
I have compiled GNU `cat` and obtained the attached WASM binary.

Running it through the transformer produces the following crash:
```
wasm-0007d6b2:333



RuntimeError: unreachable
    at __rust_start_panic (wasm-function[332]:0x16daa)
    at rust_panic (wasm-function[234]:0x1662b)
    at std::panicking::rust_panic_with_hook::h3f88564dfeb012eb (wasm-function[74]:0x1156b)
    at std::panicking::begin_panic::h9309c491ccbe032e (wasm-function[232]:0x165df)
    at wasm_transformer::generator::generate_trampolines_and_signatures::haa45f4741728f57d (wasm-function[6]:0x8c11)
    at wasm_transformer::transformer::lower_i64_wasm_for_wasi_js::h82216f0e032d580c (wasm-function[30]:0xd896)
    at wasm_transformer::lower_i64_imports::h53fe20f62b8c9bfa (wasm-function[185]:0x15b12)
    at lowerI64Imports (wasm-function[117]:0x138ee)
    at Object.module.exports.lowerI64Imports (.../wasmer-js/packages/wasm-transformer/lib/wasm-pack/node/wasm_transformer.js:69:20)
    at Object.<anonymous> (.../transform.js:5:15)
```

Here is a small JS main that just runs the transformer the way I do in my code.
```js
const fs = require('fs'), t = require('@wasmer/wasm-transformer');

const fn = 'cat.wasm';

console.log(t.lowerI64Imports(fs.readFileSync(fn)));
```

[cat.wasm.zip](https://github.com/wasmerio/wasmer-js/files/4041119/cat.wasm.zip)

**Comment by torch2424** [comment]
@corwin-of-amber Hello again! 😄 

Thank for the issue! If I . could ask just real quick, what toolchain was this compiled with? Emscripten, wasienv, rust, assemblyscript, etc... ? 

Thanks! 😄

**Comment by corwin-of-amber** [comment]
Ah sorry for the delay. I compiled it with wasi-sdk 8.
I since recompiled it and consequently it worked... I think I fixed some missing definitions in a header file (`getpagesize`), perhaps that was the reason...

**Comment by torch2424** [comment]
Ah glad you got it figured out! Yeah maybe the output of the wasm module without the correct headers led to an invalid module? 🤔 

But, you okay if we close this issue @corwin-of-amber ? 😄

**Comment by corwin-of-amber** [comment]
Well the faulty wasm that I attached still fails the transformer, so you might want to look into this even so... although ATM I was unable to reproduce how it was generated. Yes, possibly it was just corrupted for a thousand different reason. It's fine by me to close this then.

**Comment by torch2424** [comment]
@corwin-of-amber Ah good point. Let's keep this issue open then 😄 If/When I get the time to investigate this I will (Hopefully soon now that we are launching the latest feature). So yeah! Thanks again! 👍 🎉

**Comment by syrusakbary** [comment]
We just refactored the wasm-transformer in #191 .

Now it works for all the edge cases (including transforming clang! 🎉)
We also published a new version of wasmer-js: `0.9.0` that is published in npm, so you should be able to use it easily in your project! :)

Closing the issue!
Please reopen if the issue persists @corwin-of-amber

**Comment by corwin-of-amber** [comment]
Awesome! To date this cat.wasm was the only one exhibiting the problem. Did you compile clang to WASM? 😄 That is so meta. Is it also available to experiment with?

**Comment by torch2424** [comment]
Great work @syrusakbary ! :smile: :+1:

**Comment by syrusakbary** [comment]
@corwin-of-amber here we go!
https://github.com/wapm-packages/clang

**Comment by syrusakbary** [comment]
And... the tweet with a demo video!

https://twitter.com/wasmerio/status/1234903250249273344
