### ISSUE TITLE
Suggestion: try latest memfs

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer-js#182]
Greetings @torch2424 @syrusakbary,

I pushed the fix by Syrus regarding `open(..., O_DIRECTORY)` to memfs's upstream repo (https://github.com/streamich/memfs/pull/495) and it's now published as `memfs@3.0.4`.
I tried upgrading and it works smoothly, of course my testing is pretty superficial so perhaps you want to try it yourself.

If it works, the dependency on the fork (https://github.com/torch2424/memfs) can be eliminated.

**Comment by syrusakbary** [comment]
Thanks for the ping @corwin-of-amber!

**Comment by torch2424** [comment]
@corwin-of-amber Again, cannot express how cool that is that you contributed this upstream, and gave us a shout out for it! 😄 

Yes, I'll pin this issue in an open tab so I wont forget, and try to update this after our next launch tommorrow. Thanks again! 😄
