### ISSUE TITLE
wasm-terminal: Fix multi-character font support (ligatures)

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#185]
This merges these issues: 

https://github.com/wasmerio/webassembly.sh/issues/62

https://github.com/wasmerio/webassembly.sh/issues/49

With the general response:

> So this seems to work in [Hyper](https://hyper.is/). And to my understanding, they use the [xterm-addon-ligatures](https://github.com/xtermjs/xterm-addon-ligatures#requirements), which fixes the way the fonts are rendered. However, I linked to the requirements, and this addon needs system access to use the native font renderer. So we are going to half to figure out how to implement this in the browser 🤔 

So I went ahead and asked if we'd get browser support in: https://github.com/xtermjs/xterm.js/issues/958 , and can investigate other solutions later on 😄

**Comment by Michael-F-Bryan** [comment]
The `@wasmer/sdk` package is mainly focused on running WASI/WASIX programs now and leaves things like stdio or presentation to the user.
