### ISSUE TITLE
Simple command that works on wasmer cli doesn't work on wasmer-js

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#193]
This simple app just asks for input text then does nothing.

https://webassembly.sh/?run-command=wapm%20install%20richard/dice@0.0.1

https://registry-cdn.wapm.io/contents/richard/dice/0.0.1/dice.wasm

tested on wasmer 0.15.0

**Comment by syrusakbary** [comment]
I just took a look. Wasmer-js doesn't support yet multiple versions of WASI.
However the fix is trivial, so I'll make a quick release :)

**Comment by richardanaya** [comment]
Thank you!

**Comment by syrusakbary** [comment]
I just republished [WebAssembly.sh](https://webassembly.sh) with the latest Wasmer-JS (`0.10.0`) with the fix.

Dice should now be working properly! Thanks for opening the issue @richardanaya 🙂

<img width="465" alt="Screen Shot 2020-03-04 at 9 00 34 PM 1" src="https://user-images.githubusercontent.com/188257/75949478-3b691a00-5e5b-11ea-9f8b-8b1442f6d148.png">
