### ISSUE TITLE
Idea - wasmer-js could have a method for getting terminal information (or other devices)

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#195]
Making more powerful terminal apps for wasmer-js is on my mind. A great first step would be making an easy way to get the column and row width of the current terminal. An easy way for this info could be via environment variables.

Beyond this, I'm very interested also in standardized filesystem structure for getting deeper access to the current terminal. Perhaps by default a preopened directory to "/dev/" could start giving apps access to future devices. Perhaps a terminal identifier could exist in environment variables that give clues which device is representing the current terminal.

**Comment by richardanaya** [comment]
I just created my own wapm command `env` :P

i see that LINES and COLUMNS already exists now!

**Comment by richardanaya** [comment]
This is a proposal I wrote here for wasmer  https://github.com/wasmerio/wasmer/issues/1275

**Comment by Michael-F-Bryan** [comment]
I don't believe this is still relevant because the `WasmTerminal` abstraction was removed when re-writing the package as `@wasmer/sdk`.
