### ISSUE TITLE
WasmFs function overwriting does not work on WasmTerminal

### ISSUE THREAD

**Issue by FranklinWaller** [wasmerio/wasmer-js#196]
This is probably a known issue because according to the documentation you should use `@wasmer/wasi` for function overwriting but this would force developers to write their own terminal handling.

When writing a function overload on the WasmFs object it will not get called. This is probably because WasmTerminal calls fromJSON and uses that object in a Worker which loses all the connections with the original WasmFs. Now, this is fine for small applications but bigger applications don't know their file structure beforehand. With the current implementation, we would have to fetch the full directory tree and fetch all files before being able to actually run the application. 

What I would suggest is a sort of "provider" structure where WASI or WasmTerminal depends on for the files reading, writing and the directory structure. For example:

```JavaScript
const wasmTerminal = new WasmTerminal({
        fetchCommand: fetchCommandHandler,
        wasmFs,
        provider: {
            getDirectoryListing: async (path: string, listing: Listing[]) => {
                // Fetch from the server the current path
                // Would output on /:
                // /dev
                // /_wasmer
                // /myFolder
                // aFile
                return {
                    ...listing,
                    myFolder: new Folder(),
                    aFile: new File(),
                },
            },
            fetchFile: async (path: string) => {
                return new Buffer();
            },
            writeFile: async (path: string, buffer: Buffer) => {
                // Write file to server,
            }
        }
    });
```

The provider functions can be wrapped with Comlink.proxy allowing it to be transferred over to a worker and be called there. Now, this obviously doesn't cover everything but it would allow WasmTerminal to be more flexible and be used in bigger applications.

**Comment by Michael-F-Bryan** [comment]
I don't believe this is relevant any more because the `WasmTerminal` abstraction was removed when rewriting the package as `@wasmer/sdk`.
