### ISSUE TITLE
stress test discovers text rendering slowdown issues

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#197]
I developed a rather simple app that just prints random colored @ symbols again and again. There appears to be two bugs.

https://webassembly.sh/?run-command=wapm%20install%20richard/noise@0.0.8

https://github.com/richardanaya/wcurses/blob/master/examples/noise/src/lib.rs

* the text render speed is rather slow
* the text render speed gets slower and slower as time goes on

running this with wasmer has no problems at a consistent 12ish ms per frame

**Comment by richardanaya** [comment]
I wonder if this is related to https://github.com/wasmerio/wasmer-js/issues/11

**Comment by Michael-F-Bryan** [comment]
I don't believe this is relevant now that wasmer.sh uses xterm.js for rendering and is wired up to Bash compiled for WASIX. Feel free to re-open this issue if it is present with the new `@wasmer/sdk` package.
