### ISSUE TITLE
wasm-transformer: add support for lowering phase 4 proposals

### ISSUE THREAD

**Issue by neelance** [wasmerio/wasmer-js#199]
As far as I can see, nowadays Safari is very slow with adopting modern web features. All other major browsers have support for https://github.com/WebAssembly/nontrapping-float-to-int-conversions and https://github.com/WebAssembly/sign-extension-ops except Safari, including its "technology preview" version.

Unfortunately Safari is the default browser on all iOS devices and alternative browsers are required to use Safari's renderer. So it is infeasible to ship WebAssembly binaries with new features that are not supported by Safari.

This is why I would like to suggest to add support to wasm-transformer for lowering phase 4 proposals. Ideally it would do automatic feature detection and only apply the necessary lowering.

**Comment by syrusakbary** [comment]
That's a great idea!

Some of this things seem non-trivial. But we would love to collaborate on it!

**Comment by neelance** [comment]
I'm not a rust dev (yet), so I can not easily contribute directly. My current focus is on adding support for wasi to Go.

**Comment by Michael-F-Bryan** [comment]
This is implemented in Safari now.
