### ISSUE TITLE
Add better documentation for browser wasmFs (memFs)

### ISSUE THREAD

**Issue by hlolli** [wasmerio/wasmer-js#201]
I've been struggling for two days getting `preopens` working with memFs. I know I'm in a very experimental territory so it's all good. But I still fail to see any example of creating file (via open/fopen/openat) in a browser environment. I keep getting `System error : Capabilities insufficient.` but if there would be just one example of this somewhere available, I could definitely get on track.

Stay healthy, cheers!

**Comment by sfranzyshen** [comment]
things get changed faster than they get documented around here ...
