### ISSUE TITLE
wasmer-js/examples/wasm-shell/worker.ts:6:47: Cannot resolve dependency '@wasmer/wasm-terminal/workers/process.worker'

### ISSUE THREAD

**Issue by xuxuewen** [wasmerio/wasmer-js#205]
mac os

npm run dev

error:
wasmer-js/examples/wasm-shell/worker.ts:6:47: Cannot resolve dependency '@wasmer/wasm-terminal/workers/process.worker'

**Comment by sfranzyshen** [comment]
I was able to work around these type of errors by creating symbolic links within the node_modules folders to accommodate the fact that everything got moved into lib/ folders ... 
```
$ cd node_modules/@wasmer/wasm-terminal
$ ln -s lib/workers/ workers/
```
it will now find the process.worker.js file ...

**Comment by Michael-F-Bryan** [comment]
This is no longer applicable because we've rewritten the package from the ground up to implement everything in Rust, via the `wasmer-wasix` crate.
