### ISSUE TITLE
Create a method for determining if STDIN, STDOUT, STDERR are TTY

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#207]
When we pipe in data into our applications in normal operating systems in libc we normally need like a `isatty()` command to determine this. Maybe we can think of some convention for web assembly?

**Comment by ducaale** [comment]
I am currently in the process of porting a CLI tool called [xh](https://github.com/ducaale/xh) to [web assembly](https://github.com/ducaale/xh-playground) so it can be used via wasm-terminal in the browser. This program needs to check TTY to determine whether to pretty-print output and if stdin should be read or not.

I was wondering if special environment variables could be introduced to determine whether stdout/stdin is TTY or not.

```diff
diff --git a/packages/wasm-terminal/src/command-runner/command-runner.ts b/packages/wasm-terminal/src/command-runner/command-runner.ts
index af2aeb1..00272c2 100644
--- a/packages/wasm-terminal/src/command-runner/command-runner.ts
+++ b/packages/wasm-terminal/src/command-runner/command-runner.ts
@@ -81,6 +81,20 @@ export default class CommandRunner {
         this.wasmTerminalConfig,
         this.wasmTty
       );
+
+      let commandOptions = this.commandOptionsForProcessesToRun;
+      if (commandOptions.length > 1) {
+        for (let i = 0; i < commandOptions.length; i++) {
+          if (i == 0) {
+            commandOptions[i].env.STDOUT_ISNT_TTY = "1"
+          } else if (i == commandOptions.length - 1) {
+            commandOptions[i].env.STDIN_ISNT_TTY = "1"
+          } else {
+            commandOptions[i].env.STDIN_ISNT_TTY = "1"
+            commandOptions[i].env.STDOUT_ISNT_TTY = "1"
+          }
+        }
+      }
     } catch (c) {
       if (this.wasmTty) {
         this.wasmTty.print("\r\n");
```

And who knows maybe one day these environment variables could be widely adopted just like [NO_COLOR](https://no-color.org/).

**Comment by Michael-F-Bryan** [comment]
Now that the JavaScript SDK uses WASIX, WebAssembly programs can use the normal `isatty()` syscall to check whether a particular file descriptor is connected to a TTY. No changes are required in this package.
