### ISSUE TITLE
Update the wasm-transformer package?

### ISSUE THREAD

**Issue by coolreader18** [wasmerio/wasmer-js#221]
`lowerI64Imports` panics inside of wasmparser code when run in the browser, but the `wasm_transformer_cli` native binary that I built on my machine from the example works fine on the same wasm file. My only guess would be that the npm package is out of date with the latest updates to wasmparser?

**Comment by coolreader18** [comment]
Never mind, I think I was just passing an ArrayBuffer instead of a Uint8Array

**Comment by syrusakbary** [comment]
Cool, closing the issue
