### ISSUE TITLE
Cannot create file with `path_open`

### ISSUE THREAD

**Issue by corwin-of-amber** [wasmerio/wasmer-js#238]
Opening a file with a write flag should normally create the file if it does not exist, as long as the directory exists and has write permissions.

1d0eedbc9110497c885f44f26c005c92b5673729 introduced a change that stats the file before opening, causing it to throw if the file does not exist.

```js
           if (fs.statSync(full).isDirectory()) {
             realfd = fs.openSync(full, fs.constants.O_RDONLY)
           } else {
             realfd = fs.openSync(full, noflags);
           }
```

I believe the `isDirectory()` condition should only be checked if `write` is false. I am assuming `opendir` never leads to `path_open` being called with a write flag set, correct me if I'm wrong.

I'm happy to make a PR.

**Comment by syrusakbary** [comment]
The fix sounds good @corwin-of-amber !
