### ISSUE TITLE
A web app using WASI in JS, and calling Rust which shares the same Wasmer-fs

### ISSUE THREAD

**Issue by happybeing** [wasmerio/wasmer-js#250]
This is a question, is it possible for me to build a web app which uses `@wasmer/wasi` in a way that both JS modules and Rust share the same `@wasmer/wasmfs`?

I've built a test app in Svelte based on the examples which successfully uses `@wasmer/wasmfs` in the JS, and I'm trying to add some Rust to test access to the WASI filesystem, but am not sure how to do this. 

If I compile a Rust library with `--target=wasm32-wasi` I get a Rust lib (`.rlib`) which I assume is meant to be linked to generate a Rust wasm (app). So maybe I should build a Rust app, but then I don't expect this will be able to use the same WasmerJS WASI as the JavaScript.

Any idea how I can build in both JS and Rust on the same WasmerJS WASI subsystem? Thanks.

**Comment by corwin-of-amber** [comment]
Hi @happybeing, you can most definitely use the same WasmFs instance for both WA and JS, although I have never tried to used Rust (only C). In the `WASI` constructor, pass the option `bindings.fs` like so:
```js
        var wasmFs = new WasmFs();
        var wasi = new WASI({
            bindings: {
                ...WASI.defaultBindings,
                fs: wasmFs.fs,
            },
            preopens: {'/': '/'},
        });
```

The `preopens` make certain directories accessible by the WASI instance. You do have to link your Rust library into a WASM binary, I expect the result to be a `.wasm` file; looks like you created an archive but did not link it. You may have to run `wasm-ld`? I have zero experience in Rust.

**Comment by happybeing** [comment]
Thanks very much. Since posting I made some progress, I can:

- write and read files in JS to `wasmFs.fs`
- call the helloworld.wasm from the wasmerio docs and read it's output from stdout
- call the Rust HQ9+ example from the same program, and it works if I pass the control string as a parameter ("-e 'HQ9+'") and I can read its output back from stdout!

That suggests my Rust program has access to the same `wasmFs.fs`, but I'm still not able to open a file from Rust which I've created in JS, even after adding your suggested `preopens: {'/': '/'},` line. When I call the HQ9+ Rust binary with instructions to read from a file ("-f test.txt"). It tries to open the file but fails and throws an error. I've created the file in JS, so perhaps it doesn't appear in the right location - so I'll look into that.

Assuming I can get the above working, I'm still wondering if I can call Rust functions directly (rather than effectively calling `main()` every time), and have those functions able to share the WASI subsystem with everything else. Any thoughts on that? If I have to create a wasm binary, it sounds like not.

**Comment by corwin-of-amber** [comment]
Try opening the files in Rust using an absolute path; I found the notion of "cwd" in wasmer-js to not always be coherent. I've been able to work around that by `preopens: {'/': '/', '.': '.'}`, but I still had to adjust my code, esp. provide a custom `path` binding that resolves paths to their correct absolute paths within the wasmFs.

Your wasm binary can export any number of functions to the controlling runtime. You can have an empty `main()` if `WASI.start` complains about it; after `main()` exits, the `WebAssembly.Instance` is still alive and you should be able to access exported functions via `instance.exports`.

**Comment by happybeing** [comment]
@corwin-of-amber just coming back to say thanks very much. Knowing this should work helped a lot and after fixing several obscure hurdles I have proven both JS and Rust can access the `@wasmer/wasmfs` filesystem :tada: 

For anyone finding this and wanting to see it in action the code is here: https://github.com/happybeing/svelte-wasi-with-rust

I'll be adding a bit more to understand how to pass parameters to and from Rust, how to call JS from Rust etc.

**Comment by corwin-of-amber** [comment]
I'm happy to hear you managed to use WASI & wasmer-js in this cool way. Cheers.

**Comment by happybeing** [comment]
Re-opening this because I'm not sure how to take the next steps:

- call a Rust function from JS. My example ([svelte-wasi-with-rust](https://github.com/happybeing/svelte-wasi-with-rust)) has a `main()` which is called by `wasi.start(instance)` but I don't know how to export and call other Rust functions. I tried experimenting with `wasm-bindgen` but didn't get far and am not sure if that's how to do this.

- call a JS function from Rust.

I'll keep looking for an example.

**Comment by happybeing** [comment]
Update: I've made some progress but having problems calling functions with parameters using `wasm-bindgen`, see:

https://github.com/rustwasm/wasm-bindgen/issues/2422

**Comment by happybeing** [comment]
From the (closed) wasm-bindgen issue [#2422](https://github.com/rustwasm/wasm-bindgen/issues/2422):

### Summary

I'm trying to build a browser WASI app using WasmerJS and Rust. I can call parameterless Rust functions from JS and vice versa, but as soon as the Rust imports a JS function which has parameters I have a problem. This is with a WasmerJS/WASI app and the Rust compiled to target `wasm32-wasi`.

I'm not using `wasm-pack` or `cdylib` because I'm coming from a WasmerJS/WASI direction, and am not sure how to do this for target `wasm32-wasi`.

### Additional Details
The working example is on branch `main` and the error on `wasm-bindgen-jsparams` of https://github.com/happybeing/svelte-wasi-with-rust

I have a test Svelte app which uses WasmerJS/WASI in the browser, and a Rust subsystem which can share the wasmFS filesystem with the App JavaScript. I've added bindings and can call Rust/WASI functions from the App JS and vice versa, so long as I leave the Rust `main(){}` empty.

When I add parameters to my test JavaScript function and try to call this from Rust I get an error on `WebAssembly.instantiate()` in the browser console:

```
App.svelte:73 Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #2 module="./wasi-example_bg.js" error: module is not an object or function
    at startWasiTask
```
This following import only appears when the Rust is importing a JS function which has parameters, and seems to be the cause of the error:
```
(import "./wasi-example_bg.js" "__wbg_jstestn_2988839aa0c9917f" (func $wasi_example::js_test_n::__wbg_jstestn_2988839aa0c9917f::h573713d50e0d1da7 (type $t2)))
```

JavaScript being called from Rust (test.js):
```javascript
export function js_test() {
    console.log("hello from js_test()")
}

export function js_test_n(n) {
    console.log("hello from js_test_n(): ", n)
}
```
The Rust in main.rs:
```rust
#[wasm_bindgen(module = "test")]
extern "C" {
    fn js_test();
    fn js_test_n(n: u32);
 }

#[wasm_bindgen]
pub fn rust_js_test() {
    println!("Rust calling js_test()...\n");
    js_test();

    println!("Rust calling js_test_n(123)...\n");
    js_test_n(123);
}
```
This generates wasm-example_bg.js:
```javascript
import { js_test_n } from 'test';
import * as wasm from './wasi-example_bg.wasm';

function logError(f) {
    return function () {
        try {
            return f.apply(this, arguments);

        } catch (e) {
            let error = (function () {
                try {
                    return e instanceof Error ? `${e.message}\n\nStack:\n${e.stack}` : e.toString();
                } catch(_) {
                    return "<failed to stringify thrown value>";
                }
            }());
            console.error("wasm-bindgen: imported JS function that was not marked as `catch` threw an error:", error);
            throw e;
        }
    };
}

export const __wbg_jstestn_2988839aa0c9917f = logError(function(arg0) {
    js_test_n(arg0 >>> 0);
});
```
___
### Response to the above (on wasm-bindgen issue [#2422](https://github.com/rustwasm/wasm-bindgen/issues/2422)) from @corwin-of-amber:
Wow, it is thrilling to see how this project is coming along.

This is a total shot in the dark here because I don't understand what wasm-bindgen is doing; but it seems like you are expected to import the generated wasi-example_bg.js somehow. Right now your JS side (in App.svelte) just imports test, in both branches.

Then you probably need to pass that module to WASI as imports, smt along the lines of:

```imports = {'./wasi-example_bg.js': await import('./wasi-example_bg.js')}```

**Comment by happybeing** [comment]
Thanks for putting me on the right track @corwin-of-amber. I tried your suggestion, which in a way is exactly right, but solving this looks a bit more tricky. First there's a complaint from the Svelte compiler that wasi-example_bg.js "can't resolve test in ./src/wasi-example_bg.wasm", which might be fixable, but a more tricky issue is this error also from the Svelte compiler:
```
ERROR in ./src/wasi-example_bg.wasm
Module not found: Error: Can't resolve 'wasi_snapshot_preview1' in '/home/mrh/src/wasi/svelte-wasi-with-rust/src'
 @ ./src/wasi-example_bg.wasm
 @ ./src/wasi-example_bg.js
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js
```
This seems to be because `await import('./wasi-example_bg.js')` happens at compile time, causing `import * as wasm from './wasi-example_bg.wasm'` (in ./wasi-example_bg.js), I think before wasi_snapshot_preview1 exists?

I'm not sure how to solve this or even if it can be resolved within the app? Hopefully it can so I'll continue investigating how wasi works under the hood, but welcome hints from any wasi experts here!

FYI: here are all the imports from wasi-example_bg.wasm:
```
  (import "wasi_snapshot_preview1" "proc_exit" (func $__wasi_proc_exit (type $t1)))
  (import "__wbindgen_placeholder__" "__wbindgen_describe" (func $_ZN12wasm_bindgen19__wbindgen_describe17ha87a7d891479172eE (type $t1)))
  (import "__wbindgen_placeholder__" "__wbg_jstest_6119e86d65276f4c" (func $_ZN12wasi_example7js_test29__wbg_jstest_6119e86d65276f4c17h2ef4d5cfca4d08dcE (type $t0)))
  (import "__wbindgen_placeholder__" "__wbg_jstestn_2988839aa0c9917f" (func $_ZN12wasi_example9js_test_n30__wbg_jstestn_2988839aa0c9917f17h573713d50e0d1da7E (type $t1)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_grow" (func $_ZN12wasm_bindgen9externref31__wbindgen_externref_table_grow17h75ee3f8929275720E (type $t6)))
  (import "__wbindgen_externref_xform__" "__wbindgen_externref_table_set_null" (func $_ZN12wasm_bindgen9externref35__wbindgen_externref_table_set_null17h99569c4317510665E (type $t1)))
  (import "__wbindgen_placeholder__" "__wbindgen_throw" (func $_ZN12wasm_bindgen16__wbindgen_throw17hcd726668d286ae61E (type $t7)))
  (import "wasi_snapshot_preview1" "fd_write" (func $_ZN4wasi13lib_generated22wasi_snapshot_preview18fd_write17h93016769784eae7aE (type $t10)))
  (import "wasi_snapshot_preview1" "environ_sizes_get" (func $__wasi_environ_sizes_get (type $t4)))
  (import "wasi_snapshot_preview1" "environ_get" (func $__wasi_environ_get (type $t4)))
  (import "wasi_snapshot_preview1" "fd_prestat_get" (func $__wasi_fd_prestat_get (type $t4)))
  (import "wasi_snapshot_preview1" "fd_prestat_dir_name" (func $__wasi_fd_prestat_dir_name (type $t9)))
```

**Comment by happybeing** [comment]
I've tried to summarise what I think the problem is.

# Summary
I'm compiling Rust with `target=wasm32-wasi` and running `wasm-bindgen` on the `wasm-example.wasm` output. 
`wasm-bindgen` generates `wasm-example_bg.js` and `wasm-example_bg.wasm`

### `wasm-example_bg.js`
- imports `wasm-example_bg.wasm` so JS can call bindings for Rust functions exported with `#[wasm_bindgen] / pub fun name() {...}`
- imports any JS functions imported by Rust using `#[wasm_bindgen(module = "test")] / extern "C" {...}`
- provides bindings for JS to call Rust exports
- provides bindings for Wasm to call JS import (from my `test.js`)

### `wasm-example_bg.wasm` (from a Rust `wasm32-wasi` target):
- imports "test" - the imported JS functions
- imports `./wasi-example_bg.js` - for access to bindings for JS imports (from `test.js`)
- imports `wasi_snapshot_preview1` - to access the WASI API

## Problem:
- JS web app must async import ./wasi-example_bg.js before WebAssembly.instantiate() so it can provide ./wasi-example_bg.js import for the wasm
- When it does this, ./wasi-example_bg.js imports ./wasi-example_bg.wasm, and the bundler cannot resolve wasi_snapshot_preview1 which is imported by the wasm

I think the issue is a race condition where the wasm depends on the JS for JS bindings, but the JS depends on the wasm for Rust bindings which could be handled by the bundler if   wasi_snapshot_preview1 could also be resolved for the wasm.

Any thoughts on how to solve this welcome.

**Comment by MarkMcCaskey** [comment]
@happybeing So in a generalized sense, what we want is for wasm-bindgen to be able resolve imports from third party JS libraries: do you know if it can do this in other cases?

Because the generated JS is responsible for instantiating the Wasm, it needs to resolve all the imports, however it's not resolving the WASI imports, _but_ there's a pretty good reason for that (even if it does work in the general case for 3rd party imports): The WASI imports are not being seen by wasm-bindgen, they're being inserted at compile time by the compiler, so wasm-bindgen never knows about them.

If wasm-bindgen _doesn't_ have any mechanism for resolving 3rd party JS imports in any case or a setting to disable the generated JS from instantiating the Wasm, then that sounds like it's solvable on the wasm-bindgen side by adding some feature that allows this use case. However due to the implicit imports of WASI, I think the solution won't be that simple.

**Comment by happybeing** [comment]
Thanks for looking at it again @MarkMcCaskey. Actually I think I have at least a hack solution!

If I remove the import of the wasm from `wasm-example_bg.js` (as above) I can call the JS from Rust with a u32 parameter :heavy_check_mark: 

Breaking in the app after `wasi.start(instance)` I can see the Rust/WASI exports and call a Rust function from JS with a u32 parameter :heavy_check_mark: 

So I'm hopeful that by post-processing the `wasm-example_bg.js` it will be possible to have both working fairly smoothly. The approach may well work with WASI targets in general, not just WasmerJS, but I don't know enough to say if that's the case.

Either way, if I can show how to do this and it may make a good case for adding an option to `wasm-bindgen` to simplify this if needed.

I thought it was going to be much tricker than this but fingers crossed I can make this work and expand the example to demonstrate the full capabilities of `wasm-bindgen` in this scenario.

Thanks very much both @MarkMcCaskey and @corwin-of-amber for your encouragement and pointers. I'm really excited to see this coming together and you've both helped a lot. :pray:

**Comment by MarkMcCaskey** [comment]
Glad to hear you're making progress! One thing to be aware of is that any function marked with `#[wasm_bindgen]` may be mutated arbitrarily as far as I can tell: that means the only correct way to call functions marked with `#[wasm_bindgen]`, in general, is through the generated JS (which was generated in sync with the mutations to the Rust/Wasm function)

**Comment by happybeing** [comment]
Thanks for the heads up. If need be, I should be able to extract those functions from the `wasm-bindgen` output into a separate file, and modify them to use the implementations on `instance.exports` rather than the imported wasm. It will be a hack, but that's what hackers do huh? :sunglasses:

**Comment by happybeing** [comment]
I've solved this issue and produced an example which uses `wasm-bindgen` with WasmerJS and Rust/WASI (target wasm32-wasi). See: https://github.com/happybeing/svelte-wasi-with-rust

The result is really impressive. Easy to implement, easy to use and the release build is tiny 200k for the JS bundle and 200k. This compares to for 12MB for Go/Wasm (not using WasmerJS or WASI) because of the Go runtime, and I prefer Rust anyway.

I included a few examples of passing different types using `wasm-bindgen` but would like more so PRs or pointers to code are welcome. You can see the examples I have so far in [main.rs](https://github.com/happybeing/svelte-wasi-with-rust/blob/main/src/rust-wasi-example/src/main.rs).

@MarkMcCaskey and @corwin-of-amber  thank you both very much for your help and encouragement!
