### ISSUE TITLE
Consider using performance.now() to improve time API precision

### ISSUE THREAD

**Issue by vshymanskyy** [wasmerio/wasmer-js#252]
Currently Date.now() is used, which has very limited precision.
AFAIK, `performance.timing.navigationStart` can be added to `performance.now()` to get the absolute time reference.

**Comment by syrusakbary** [comment]
That’s a good point! Happy to accept a PR if you would like to contribute!

**Comment by syrusakbary** [comment]
The newest release should be using performance.now.

Closing the issue!
