### ISSUE TITLE
Rollup creates broken path binding

### ISSUE THREAD

**Issue by artlogic** [wasmerio/wasmer-js#253]
I've been having trouble using these modules with bundlers other than rollup (e,g, webpack). I kept receiving an error about problems with the path module, which is bundled. I've found that using the published ESM I need to do the following to make the bundled path module work:

```javascript
  const wasi = new WASI({
    // Bindings that are used by the WASI Instance (fs, path, etc...)
    bindings: {
      ...WASI.defaultBindings,
      fs: wasmFs.fs,
      // the current WASI bundle of path is broken!
      path: WASI.defaultBindings.path.default,
    },
  });
```

Notice that the path object is exposing a default property instead of just an object. I have a feeling this has something to do with this issue: https://github.com/rollup/plugins/issues/481

**Comment by Michael-F-Bryan** [comment]
The `@wasmer/wasi` package was rewritten and renamed to `@wasmer/sdk`, so I don't believe this is an issue any more.
