### ISSUE TITLE
Example and wasm-terminal use undocumented API (wasmerFs.volume.fds[1].write)

### ISSUE THREAD

**Issue by Artoria2e5** [wasmerio/wasmer-js#263]
When looking for a way to get stdout as it is produced, I stumbled upon the use of `wasmerFs.volume.fds[1].write` in the source code, the purpose of which is pretty self-explanatory from the naming. The unfortunate thing is that the chain is basically undocumented:

* wasmerFs.volume is not yet documented as pointing to a memfs `Volume`. This can be fixed easily on wasmerio docs.
* memfs's `Volume` is not documented to have `fds` in their markdown API reference either. Now that's someone else's problem, and it makes things messier because I am familiar with neither wasmer-js nor memfs.

It should also be noted that the JSON stuff in wasmerFs are not documented anywhere either -- neither in the `ts` source nor in the reference API `md` at https://docs.wasmer.io/integrations/js/reference-api/wasmer-wasmfs. Any chance we can find a way to write the doc once and have the other thing be generated somehow?

**Comment by syrusakbary** [comment]
We moved away from memfs into a pure rust/wasm FS implementation.

Closing the issue :)
