### ISSUE TITLE
wasmer-js implementation of poll_oneoff for WASI_EVENTTYPE_CLOCK is still using wasi_unstable memory layout

### ISSUE THREAD

**Issue by jrandall** [wasmerio/wasmer-js#272]
It appears that the wasmer-js implementation of `poll_oneoff` for `WASI_EVENTTYPE_CLOCK` is still using the old `wasi_unstable` (snapshot_0) memory layout.

In `wasi_unstable` (snapshot_0), the `subscription_clock` struct was 40 bytes and included an 8-byte `identifier` field: 
https://github.com/WebAssembly/WASI/blob/main/phases/old/snapshot_0/docs.md#subscription_clock

In `wasi_snapshot_preview1`, the `subscription_clock` struct is now 32 bytes and does not include an 8-byte `identifier` field. 
https://github.com/WebAssembly/WASI/blob/main/phases/snapshot/docs.md#subscription_clock

When `wasmer-js` is used by code written to the `wasi_snapshot_preview1` spec, this results in a null response to `now(clockid)` because the `clockid` is read from the wrong part of memory. 

The fix for this issue (for `wasi_snapshot_preview1`) is to remove these two lines:
https://github.com/wasmerio/wasmer-js/blob/master/packages/wasi/src/index.ts#L1386-L1387

However, I am not sure how/whether wasmer-js intends to support both `wasi_unstable` and `wasi_snapshot_preview1` at the same time (a quick check did not suggest any instances where a different code path is chosen depending on the version).

**Comment by syrusakbary** [comment]
This should be fixed with the new implementation
