### ISSUE TITLE
Put the name of the wasm file as the first value of the result of `args_get`?

### ISSUE THREAD

**Issue by igrep** [wasmerio/wasmer-js#274]
Contrary to [wasmer's implementation](https://github.com/wasmerio/wasmer/blob/99b24a9eb199ecd269a4149c4478d65a09027c8b/lib/wasi/src/state/builder.rs#L12), wasmer-js doesn't have any parameters to set the wasm file's name as the first value of the arguments ([ref](https://github.com/wasmerio/wasmer-js/blob/4c34bb0e584cc24036c3d6d7419550ff9c9ab502/packages/wasi/src/index.ts#L376)), if I read the source code and document correctly. I know this is just because wasmer-js followed Node.js's WASI, while wasmer reproduces the existing command runners' behavior.
Anyway, this can be a cause of inconsistent behavior between host applications and I don't think WASI executables are responsible for handling this difference.

Related issue of WASI: https://github.com/WebAssembly/wasi-classic-command/issues/7

**Comment by Michael-F-Bryan** [comment]
You can do this with the new SDK using the `program` argument for `RunOptions`.

https://github.com/wasmerio/wasmer-js/blob/d6ed31b7463ba1350022571438262f6a58061558/src/options.rs#L50-L51

It'll be automatically derived from the command name if using a package from the Wasmer registry.
