### ISSUE TITLE
Path bindings for path-browserify not working

### ISSUE THREAD

**Issue by fritzbauer** [wasmerio/wasmer-js#281]
The code in https://github.com/wasmerio/wasmer-js/blob/master/packages/wasi/src/bindings/browser.ts#L21
`path: path,` gets transpiled to:
 `path: path_browserify_1.default,`
However, there is no export "default" in the path-browserify module. Therefore the path binding will be undefined and the WASI interface will not work correctly. 
Manually changing it to "posix"  in the index.js resolves the issue for me. Not sure how to fix it in TypeScript:
https://github.com/browserify/path-browserify/blob/4df8c2ae7efbecf54538aafc34b295c0934f256e/index.js#L529

**Comment by syrusakbary** [comment]
Wasmer 1.0 no longer uses the typescript implementation. Closing the issue as this should be now solved :)
