### ISSUE TITLE
How is blocking behavior in poll_oneoff handled in the browser?

### ISSUE THREAD

**Issue by TerrorJack** [wasmerio/wasmer-js#288]
In the legacy `0.x` branch, `poll_oneoff` can only handle clock events, and it keeps spinning until the timeout has reached, which will block the whole event loop (https://github.com/wasmerio/wasmer-js/blob/0.x/packages/wasi/src/index.ts#L1369). Is this still the case for the current version?

**Comment by syrusakbary** [comment]
In the current version we skipped `poll_oneoff` because it added too much weight to the wasm. We could re-add it back with tokio soon

**Comment by sigma-andex** [comment]
@syrusakbary is there any news on this? or how could I make this available? I'm trying to run a simple [hello world](https://github.com/sigma-andex/wasm-test) which I compiled from Haskell.
I'm getting an error and my understanding is that `__wasi_poll_oneoff@http://localhost:5173/test.wasm:wasm-function[4813]:0x126747` is not available.
<details>
  <summary>Full error message</summary>
  Uncaught Error: Error while running start function: RuntimeError: JsValue(RuntimeError: unreachable executed
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[667]:0x73220
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[982]:0x79dd4
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[439]:0x57b3c
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[70]:0x2890
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[455]:0x64fad
__wasi_poll_oneoff@http://localhost:5173/test.wasm:wasm-function[4813]:0x126747
poll@http://localhost:5173/test.wasm:wasm-function[4788]:0x1259cb
fdReady@http://localhost:5173/test.wasm:wasm-function[1427]:0x58d35
base_GHCziIOziFD_zdwwriteRawBufferPtr_entry@http://localhost:5173/test.wasm:wasm-function[1488]:0x5aed5
StgRun@http://localhost:5173/test.wasm:wasm-function[4203]:0xe3aa9
scheduleWaitThread@http://localhost:5173/test.wasm:wasm-function[4160]:0xe032e
rts_evalLazyIO@http://localhost:5173/test.wasm:wasm-function[4017]:0xd56de
hs_main@http://localhost:5173/test.wasm:wasm-function[4020]:0xd5876
main@http://localhost:5173/test.wasm:wasm-function[28]:0x6f24
__main_void@http://localhost:5173/test.wasm:wasm-function[4817]:0x12682b
_start@http://localhost:5173/test.wasm:wasm-function[21]:0x6a75
_start.command_export@http://localhost:5173/test.wasm:wasm-function[4947]:0x132514
x/B2.wbg.__wbg_apply_0b1f3c47d1bbe0ea/<@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e:624:24
U@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e:196:15
x/B2.wbg.__wbg_apply_0b1f3c47d1bbe0ea@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e:623:12
@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e line 665 > WebAssembly.compile:wasm-function[106]:0x2d182
start@http://localhost:5173/node_modules/.vite/deps/@wasmer_wasi.js?v=c5b6a40e:385:14
@http://localhost:5173/main.js:23:21
)
    __wbg_new_342a24ca698edd87 Library.esm.min.js:25
    start Library.esm.min.js:25
    <anonymous> main.js:23
[Library.esm.min.js:25:12963](http://localhost:5173/node_modules/@wasmer/wasi/dist/Library.esm.min.js)
    __wbg_new_342a24ca698edd87 Library.esm.min.js:25
    <anonymous> @wasmer_wasi.js:185970
    start Library.esm.min.js:25
    <anonymous> main.js:23
    AsyncFunctionNext self-hosted:668
</details>

**Comment by corwin-of-amber** [comment]
FWIW, there is no facility (that I am aware of) in WASM to "yield", that is unwind the stack and hand control over to the main thread with the ability to resume from the same point later. So coroutine-like operations in C programs that were not designed to be async is not really possible, you will have to write your C code to facilitate this.

Two options come to mind:
 * Write your async event loop in JS and issue calls to C that will not have to block. If you need a timeout, it would mean that you will have to `setTimeout` in JS.
 * Run the WASM in a Web Worker and use SharedArrayBuffer + Atomics to communicate between the worker and the main thread, like I did in https://github.com/corwin-of-amber/wasi-kernel/blob/master/src/kernel/streams.ts. This will allow you to implement a polyfill where the worker is "blocked" but the UI is still operational. Again you will need to `setTimeout` from the main thread but at least the worker will resume from where it was.

**Comment by Michael-F-Bryan** [comment]
The new `@wasmer/sdk` package now runs WebAssembly code in a Web Worker in the background, which means it won't block the browser's event loop. Spawning a WASIX program, communicating with it, and waiting for it to exit are now all asynchronous operations.

I don't know the exact commit to the `wasmer-wasix` crate which fixed it, but syscalls like `poll_oneoff` are now backed by Rust futures and will go to sleep ([`Atomic.wait()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait) in the browser) until it is ready. Executing WebAssembly code will still block, but at least it won't do a busy wait and peg your CPU to 100%.

We also allow WASIX binaries to do networking and use `epoll()`, it's just that the networking layer hasn't been wired up to `@wasmer/sdk` yet, so users can't access it.
