### ISSUE TITLE
@wasmer/wasi: Document Demo Fail

### ISSUE THREAD

**Issue by sinoon** [wasmerio/wasmer-js#292]
The Demo in : https://docs.wasmer.io/integrations/js/reference-api/wasmer-wasi 

```js
const browserBindings = require("@wasmer/wasi/lib/bindings/browser");
// for Node:
// const nodeBindings = require("@wasmer/wasi/lib/bindings/node");

// omit other part
```

That has am error: `Cannot resolve dependency '@wasmer/wasi/lib/bindings/browser`

![image](https://user-images.githubusercontent.com/6065488/163153820-864f2bef-b86a-4dd8-8326-baefd57271cd.png)

After look inside, @wasmer/wasi `"@wasmer/wasi": "^0.10.0"` has directory `lib` in npm module, but the latest version does't.

So, the question is, is there the way run wasi in browser?

**Comment by nicobytes** [comment]
I have the same problem. I tried to follow the official example in the docs, but it shows an error:

```sh
 Failed to resolve '@wasmer/wasi/lib/bindings/browser' from './src/index.js'
```

<img width="760" alt="image" src="https://user-images.githubusercontent.com/7611944/165823718-8807e56c-bc02-4ff4-a0da-9db29fc4650a.png">

Then try to run the official [example for Nodejs](https://github.com/wasmerio/wasmer-js/blob/main/examples/node/helloworld.mjs), like this:

```js
import fs from "fs";
import { init, WASI } from "@wasmer/wasi";

// This is needed to load the WASI library first
await init();

let wasi = new WASI({
  env: {},
  args: [],
});

const buf = fs.readFileSync('./src/demo.wasm');

const module = await WebAssembly.compile(
  new Uint8Array(buf)
);
await wasi.instantiate(module, {});

let exitCode = wasi.start();
let stdout = wasi.getStdoutString();
// This should print "hello world (exit code: 0)"
console.log(`${stdout}(exit code: ${exitCode})`);
```

NodeJS works, but in the browser doesn't work, I tried adjusting the NodeJS example to browser using fetch, like this:

```js
import { init, WASI } from "@wasmer/wasi";

await init();

let wasi = new WASI({
  env: {},
  args: [],
});

let response  = await fetch('/demo.wasm');
let wasmBytes = new Uint8Array(await response.arrayBuffer());

const module = await WebAssembly.compile(wasmBytes);
await wasi.instantiate(module, {});

let exitCode = wasi.start();
let stdout = wasi.getStdoutString();
// This should print "hello world (exit code: 0)"
console.log(`${stdout}(exit code: ${exitCode})`);
```

But it shows the following error:

```sh
 Failed to resolve 'wasmer_wasi_js_bg.wasm' from './node_modules/@wasmer/wasi/dist/Library.esm.min.js'
```

<img width="932" alt="image" src="https://user-images.githubusercontent.com/7611944/165824502-da3a699a-0a7b-4a18-9e4e-33798471bd7b.png">

**Comment by c4lliope** [comment]
The missing `wasmer_wasi_js_bg.wasm` can be marked as an "external" if you are compiling using `webpack`.
The error has already been discussed in https://github.com/wasmerio/wasmer-js/issues/290.

**Comment by outkine** [comment]
The solution from #290 does resolve the `cannot load file` error, but I'm now encountering `ReferenceError: Buffer is not defined`. So returning to the original question: since it seems that the browser bindings file has been removed, does that mean that it's no longer possible to run wasi in the browser?

**Comment by corwin-of-amber** [comment]
The outdated reference to `@wasmer/wasi/lib/bindings/browser` in the documentation as pointed out by @sinoon and @nicobytes is a hinderance. Can you please remove it?

Also probably should add a note about the `external` config which is required for Webpack users.

**Comment by syrusakbary** [comment]
We have published a new version of `@wasmer/wasi` which no longer has the issue I believe. I'll work on updating the wasmer docs :)
