### ISSUE TITLE
Where is the source code of "wasmer_wasi_js_bg.wasm"?

### ISSUE THREAD

**Issue by llxStar** [wasmerio/wasmer-js#297]
Hi guys，
    Thanks for [wasmer-js](https://github.com/wasmerio/wasmer-js),it is helpful to me.I want to find the source code of "wasmer_wasi_js_bg.wasm" and add my code in.I want to base on "wasmer_wasi_js_bg.wasm" to build my App.I have found [wamser](https://github.com/wasmerio/wasmer) but not here.Can i get the source code or How can i build it?
   Thanks wasmerio again!

**Comment by epilys** [comment]
`*_bg.wasm` files are generated by `wasm-bindgen`. They include code and/or shims that are required for your project.

**Comment by corwin-of-amber** [comment]
@llxStar it is basically `src/wasi.rs` compiled with wasm-bindgen as `epilys` mentioned. That of course links with the wasmer lib that you have found. Cargo takes care of the linking.
