### ISSUE TITLE
Instantiate WebAssembly modules asynchronously

### ISSUE THREAD

**Issue by Michael-F-Bryan** [wasmerio/wasmer-js#314]
In #311, @sigmaSd noticed that the `Wasi.instantiate()` method is synchronous, which implies `wasmer` is [synchronously calling the `new WebAssembly.Instance()` constructor](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Instance#synchronously_instantiating_a_webassembly_module).

Ideally, we would use something promise-based like [`WebAssembly.instantiateStreaming()`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming) so we don't block the main event loop.

This may require some reworking of the `wasmer::js` module's internals. Probably around [here](https://github.com/wasmerio/wasmer/blob/ecde2aa8f454b4ace057ee06319fe8dafff95ea6/lib/api/src/js/module.rs#L279-L280) where we instantiate modules.

**Comment by syrusakbary** [comment]
Hey @Michael-F-Bryan, we can actually skip using `Instance::new` all together and actually do the instantiate streaming directly via the wasm-bindgen JS API in this codebase (we already support providing directly an instance to the WASI API):

https://github.com/wasmerio/wasmer-js/blob/main/tests/index.spec.js#L85-L90

**Comment by Michael-F-Bryan** [comment]
This should be resolved with the `@wasmer/sdk` rewrite.
