### ISSUE TITLE
markdown-renderer is not doing anything; returning original string.

### ISSUE THREAD

**Issue by archywillhe** [wasmerio/wasmer-js#401]
### Describe the bug

I'm trying the markdown-renderer example. 

`await Wasmer.fromRegistry("wasmer-examples/markdown-renderer");` have loaded something - but it's not doing anything markdown related. It just returns the original string. 

### Steps to reproduce

go to example's markdown-renderer

Here is my wasm version 

```sh
wasmer 4.2.5 (0460050 2023-12-23)
binary: wasmer-cli
commit-hash: 04600507844bae978239531c8e6265d410aefe6d
commit-date: 2023-12-23
host: aarch64-apple-darwin
compiler: singlepass,cranelift
rustc 1.76.0-nightly (f704f3b93 2023-12-19)
binary: rustc
commit-hash: f704f3b93b1543cf504ecca0052f9f8531b1f61f
commit-date: 2023-12-19
host: aarch64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.6
```

**Comment by kandros** [comment]
I noticed it, it happens to also my own version of it 

BUT
- It works when invoked via CLI
-  loading from local file works

https://github.com/wasmerio/docs.wasmer.io/issues/81
