### ISSUE TITLE
xterm bash example fails

### ISSUE THREAD

**Issue by o-az** [wasmerio/wasmer-js#436]
https://github.com/wasmerio/wasmer-js/blob/main/examples/wasmer.sh/vite.config.js#L10

in vite config fs allow path is `../..`.
What exactly are the files this example needs from that path? I will copy them over manually to my example

**Comment by o-az** [comment]
here's what I did so far:


- I cloned only this directory: https://github.com/wasmerio/wasmer-js/tree/main/examples/wasmer.sh

- updated [this line](https://github.com/wasmerio/wasmer-js/blob/main/examples/wasmer.sh/package.json#L22) with the latest published version

- run build, success, run `dev`, get the following error in the browser:
	```sh
	index.ts:89 Uncaught (in promise) CompileError:
	WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0
	```

My only guess is it's related to this:

https://github.com/wasmerio/wasmer-js/blob/main/examples/wasmer.sh/vite.config.js#L10

**Comment by syrusakbary** [comment]
I did added one simple fix in main: https://github.com/wasmerio/wasmer-js/commit/845dfd194a6f87d70c29327ce363e9e46c083408

I think that should fix your issue. Let me know if it persists @o-az
