### ISSUE TITLE
wasmer.sh example doesn't work 

### ISSUE THREAD

**Issue by ambrt** [wasmerio/wasmer-js#441]
Hi

I cloned `examples/wasmer.sh`, added SDK and tried to run it.

 It creates start of a terminal but then it throws uncaught error:
`Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5173/node_modules/.vite/deps/index.mjs`

Vite shows error:
```The file does not exist at "/home/user/wasmer/examples/node_modules/.vite/deps/index.mjs" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.```

Searching in Vite's repo didn't show anything useful.

Ubuntu, Chrome.

**Comment by syrusakbary** [comment]
It seems that `npm i` was not run in the examples. Closing the issue
